version: '3'

services:

    webhook:
        build: .
        restart: unless-stopped
        ports:
            - 41523:41523

    db:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - ./redis-data:/var/lib/redis
